import streamlit as st
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import NearestNeighbors

# --- Dataset simplificado para demostración (usa el tuyo completo en producción) ---
data = {
  "busqueda": [
    "accesorios para mascotas",
    "bicicletas de montaña",
    "bicicleta estatica",
    "coches electricos",
    "consolas de nueva generacion",
    "documentales sobre salud",
    "juegos de estrategia",
    "decoracion de interiores",
    "hoteles baratos",
    "accesorios para mascotas",
    "mochilas de senderismo",
    "batidos de proteina",
    "motos deportivas",
    "drone para fotografia",
    "libros de autoayuda",
    "peliculas de accion",
    "herramientas de jardin",
    "power bank para viajes",
    "alimento premium gatos",
    "zapatos de senderismo",
    "suplementos fitness",
    "coches electricos",
    "mouse gamer",
    "recetas veganas",
    "libros de misterio",
    "sillas ergonomicas",
    "hoteles baratos",
    "correas para perros",
    "bicicletas de montaña",
    "zapatillas deportivas",
    "motos deportivas",
    "smartwatch deportivo",
    "yoga principiantes",
    "peliculas de ciencia ficcion",
    "plantas de interior",
    "cargador solar portátil",
    "accesorios para mascotas",
    "zapatos de senderismo",
    "ropa de ejercicio",
    "coches electricos",
    "teclado mecanico",
    "aplicaciones de recetas",
    "series de fantasia",
    "escritorios ajustables",
    "viajes a la playa",
    "alimento premium gatos",
    "mochilas de senderismo",
    "calcetines deportivos",
    "motos deportivas",
    "auriculares gamer",
    "meditacion guiada",
    "videojuegos de rol",
    "macetas decorativas",
    "cargador solar portátil",
    "correas para perros",
    "bicicletas de montaña",
    "entrenamiento en casa",
    "coches electricos",
    "pantalla 4K",
    "recetas saludables",
    "peliculas romanticas",
    "pantallas LED decorativas",
    "viajes a la playa",
    "alimento premium gatos",
    "zapatos de senderismo",
    "camisetas running",
    "motos deportivas",
    "reloj Garmin",
    "colchoneta yoga",
    "series policiacas",
    "luces inteligentes",
    "hoteles baratos",
    "accesorios para mascotas",
    "mochilas de senderismo",
    "mancuernas ajustables",
    "coches electricos",
    "auriculares inalambricos gym",
    "tupper saludables",
    "peliculas de ciencia ficcion",
    "robots de limpieza",
    "cargador solar portátil",
    "correas para perros",
    "zapatos de senderismo",
    "ropa termica para correr",
    "motos deportivas",
    "camara deportiva",
    "libros de autoayuda",
    "juegos de estrategia",
    "herramientas de jardin",
    "power bank para viajes",
    "accesorios para mascotas",
    "bicicletas de montaña",
    "pesas rusas",
    "coches electricos",
    "smartwatch deportivo",
    "documentales sobre salud",
    "series de fantasia",
    "decoracion de interiores",
    "hoteles baratos",
    "alimento premium gatos",
    "mochilas de senderismo",
    "zapatillas deportivas",
    "motos deportivas",
    "consolas de nueva generacion",
    "recetas saludables",
    "peliculas de accion",
    "plantas de interior",
    "viajes a la playa",
    "correas para perros",
    "zapatos de senderismo",
    "ropa de ejercicio",
    "coches electricos",
    "mouse gamer",
    "yoga principiantes",
    "libros de misterio",
    "sillas ergonomicas",
    "hoteles baratos",
    "accesorios para mascotas",
    "bicicletas de montaña",
    "suplementos fitness",
    "motos deportivas",
    "teclado mecanico",
    "aplicaciones de recetas",
    "videojuegos de rol",
    "escritorios ajustables",
    "cargador solar portátil",
    "alimento premium gatos",
    "mochilas de senderismo",
    "bicicleta estatica",
    "coches electricos",
    "auriculares gamer",
    "meditacion guiada",
    "peliculas romanticas",
    "macetas decorativas",
    "power bank para viajes",
    "correas para perros",
    "zapatos de senderismo",
    "camisetas running",
    "motos deportivas",
    "reloj Garmin",
    "colchoneta yoga",
    "series policiacas",
    "pantallas LED decorativas",
    "viajes a la playa",
    "accesorios para mascotas",
    "bicicletas de montaña",
    "entrenamiento en casa",
    "motos deportivas",
    "pantalla 4K",
    "recetas veganas",
    "peliculas de ciencia ficcion",
    "luces inteligentes",
    "hoteles baratos",
    "alimento premium gatos",
    "zapatos de senderismo",
    "batidos de proteina",
    "coches electricos",
    "auriculares inalambricos gym",
    "tupper saludables",
    "juegos de estrategia",
    "robots de limpieza"
  ],
  "tema_interes": [
    "mascotas",
    "deportes al aire libre",
    "fitness",
    "movilidad sostenible",
    "videojuegos",
    "salud",
    "entretenimiento",
    "hogar",
    "viajes",
    "mascotas",
    "accesorios de montaña",
    "nutrición",
    "motociclismo",
    "fotografía aérea",
    "crecimiento personal",
    "cine",
    "jardinería",
    "tecnología portátil",
    "mascotas",
    "accesorios de montaña",
    "nutrición deportiva",
    "movilidad sostenible",
    "gaming",
    "alimentación saludable",
    "lectura",
    "oficina saludable",
    "viajes",
    "mascotas",
    "deportes al aire libre",
    "ropa deportiva",
    "motociclismo",
    "wearables",
    "bienestar",
    "cine",
    "decoración",
    "energía renovable",
    "mascotas",
    "accesorios de montaña",
    "ropa deportiva",
    "movilidad sostenible",
    "tecnología",
    "alimentación saludable",
    "entretenimiento",
    "ergonomía",
    "turismo",
    "mascotas",
    "accesorios de montaña",
    "ropa deportiva",
    "motociclismo",
    "gaming",
    "bienestar",
    "videojuegos",
    "hogar",
    "energía renovable",
    "mascotas",
    "deportes al aire libre",
    "otro",
    "movilidad sostenible",
    "cine",
    "salud",
    "cine",
    "hogar inteligente",
    "turismo",
    "mascotas",
    "accesorios de montaña",
    "otro",
    "motociclismo",
    "wearables",
    "bienestar",
    "entretenimiento",
    "hogar inteligente",
    "viajes",
    "mascotas",
    "accesorios de montaña",
    "fitness",
    "movilidad sostenible",
    "tecnología deportiva",
    "salud",
    "cine",
    "hogar inteligente",
    "energía renovable",
    "mascotas",
    "accesorios de montaña",
    "ropa deportiva",
    "motociclismo",
    "cámara de acción",
    "crecimiento personal",
    "entretenimiento",
    "jardinería",
    "tecnología portátil",
    "mascotas",
    "deportes al aire libre",
    "fitness",
    "movilidad sostenible",
    "wearables",
    "salud",
    "entretenimiento",
    "hogar",
    "viajes",
    "mascotas",
    "accesorios de montaña",
    "ropa deportiva",
    "motociclismo",
    "videojuegos",
    "salud",
    "cine",
    "decoración",
    "turismo",
    "mascotas",
    "accesorios de montaña",
    "ropa deportiva",
    "movilidad sostenible",
    "gaming",
    "bienestar",
    "lectura",
    "oficina saludable",
    "viajes",
    "mascotas",
    "deportes al aire libre",
    "nutrición deportiva",
    "motociclismo",
    "tecnología",
    "alimentación saludable",
    "videojuegos",
    "ergonomía",
    "energía renovable",
    "mascotas",
    "accesorios de montaña",
    "fitness",
    "movilidad sostenible",
    "gaming",
    "bienestar",
    "cine",
    "hogar",
    "tecnología portátil",
    "mascotas",
    "accesorios de montaña",
    "otro",
    "motociclismo",
    "wearables",
    "bienestar",
    "entretenimiento",
    "hogar inteligente",
    "turismo",
    "mascotas",
    "deportes al aire libre",
    "otro",
    "motociclismo",
    "cine",
    "alimentación saludable",
    "cine",
    "hogar inteligente",
    "viajes",
    "mascotas",
    "accesorios de montaña",
    "nutrición",
    "movilidad sostenible",
    "tecnología deportiva",
    "salud",
    "entretenimiento",
    "hogar inteligente"
  ],
  "anuncio_sugerido": [
    "Arnés Julius-K9 IDC Power para perros",
    "Bicicleta Trek Marlin 7 con suspensión delantera",
    "Bicicleta Estática Schwinn IC4 con Bluetooth",
    "Tesla Model 3 Long Range AWD 2024",
    "PlayStation 5 Edición Digital",
    "Colección de documentales 'Heal' en Blu-ray",
    "Juego de mesa Catan Edición 25 Aniversario",
    "Set de cuadros minimalistas Nordic para sala",
    "Suscripción Booking.com Genius Level 3",
    "Arnés Julius-K9 IDC Power para perros",
    "Mochila The North Face Terra 55L",
    "Proteína Gold Standard 100% Whey 2.27 kg",
    "Yamaha YZF-R3 ABS 2024",
    "DJI Mini 3 Pro con control remoto RC",
    "Libro 'Los 7 hábitos de la gente altamente efectiva'",
    "Colección Blu-ray John Wick Trilogía",
    "Kit Black+Decker de jardinería 5 piezas",
    "Anker PowerCore 26800mAh con carga rápida",
    "Royal Canin Feline Health Nutrition Indoor",
    "Botas Merrell Moab 3 Mid Waterproof",
    "Creatina Micronizada Optimum Nutrition 300g",
    "Tesla Model 3 Long Range AWD 2024",
    "Logitech G502 HERO RGB 25K",
    "Libro 'Veganomicon' – Cocina vegana gourmet",
    "Libro 'La chica del tren' de Paula Hawkins",
    "Silla ergonómica SIHOO M18 con soporte lumbar",
    "Suscripción Booking.com Genius Level 3",
    "Correa retráctil Flexi Giant 8m",
    "Bicicleta Trek Marlin 7 con suspensión delantera",
    "Nike Air Zoom Pegasus 40",
    "Yamaha YZF-R3 ABS 2024",
    "Garmin Forerunner 255 Music",
    "Kit de Yoga Gaiam Essentials con mat y bloques",
    "Colección Blu-ray Star Wars Saga",
    "Planta Sansevieria en maceta decorativa",
    "Panel solar portátil BigBlue 28W USB",
    "Arnés Julius-K9 IDC Power para perros",
    "Botas Merrell Moab 3 Mid Waterproof",
    "Leggings deportivos Gymshark Adapt",
    "Tesla Model 3 Long Range AWD 2024",
    "Teclado mecánico Razer BlackWidow V4",
    "Suscripción anual a FitMenCook App",
    "Boxset Blu-ray Game of Thrones Completa",
    "Escritorio eléctrico FLEXISPOT EG1",
    "Sombrilla Tommy Bahama con anclaje de arena",
    "Royal Canin Feline Health Nutrition Indoor",
    "Mochila The North Face Terra 55L",
    "Calcetines Nike Everyday Cushion 3 pares",
    "Yamaha YZF-R3 ABS 2024",
    "Auriculares HyperX Cloud II Wireless",
    "Suscripción anual a la app Calm Premium",
    "The Legend of Zelda: Tears of the Kingdom",
    "Set de 3 macetas cerámicas estilo nórdico",
    "Panel solar portátil BigBlue 28W USB",
    "Correa retráctil Flexi Giant 8m",
    "Bicicleta Trek Marlin 7 con suspensión delantera",
    "Producto destacado relacionado con: entrenamiento en casa",
    "Tesla Model 3 Long Range AWD 2024",
    "Samsung Smart TV 55” 4K UHD Crystal",
    "Libro 'Cocina sana para disfrutar' – Isasaweis",
    "Colección Blu-ray 'Antes del amanecer' trilogía",
    "Tira LED Govee RGBIC con control app",
    "Sombrilla Tommy Bahama con anclaje de arena",
    "Royal Canin Feline Health Nutrition Indoor",
    "Botas Merrell Moab 3 Mid Waterproof",
    "Producto destacado relacionado con: camisetas running",
    "Yamaha YZF-R3 ABS 2024",
    "Garmin Fenix 7 Solar",
    "Colchoneta Manduka PRO Yoga Mat 6mm",
    "Boxset Blu-ray Sherlock BBC completa",
    "Philips Hue White & Color Ambiance Kit",
    "Suscripción Booking.com Genius Level 3",
    "Arnés Julius-K9 IDC Power para perros",
    "Mochila The North Face Terra 55L",
    "Mancuernas ajustables Bowflex SelectTech 552",
    "Tesla Model 3 Long Range AWD 2024",
    "Jabra Elite 7 Active True Wireless",
    "Set de Tuppers Rubbermaid Brilliance BPA-Free",
    "Colección Blu-ray Star Wars Saga",
    "iRobot Roomba j7+ con estación de vaciado",
    "Panel solar portátil BigBlue 28W USB",
    "Correa retráctil Flexi Giant 8m",
    "Botas Merrell Moab 3 Mid Waterproof",
    "Camiseta térmica Under Armour ColdGear",
    "Yamaha YZF-R3 ABS 2024",
    "GoPro Hero 12 Black",
    "Libro 'Los 7 hábitos de la gente altamente efectiva'",
    "Juego de mesa Catan Edición 25 Aniversario",
    "Kit Black+Decker de jardinería 5 piezas",
    "Anker PowerCore 26800mAh con carga rápida",
    "Arnés Julius-K9 IDC Power para perros",
    "Bicicleta Trek Marlin 7 con suspensión delantera",
    "Pesa rusa Kettlebell Amazon Basics 12kg",
    "Tesla Model 3 Long Range AWD 2024",
    "Garmin Forerunner 255 Music",
    "Colección de documentales 'Heal' en Blu-ray",
    "Boxset Blu-ray Game of Thrones Completa",
    "Set de cuadros minimalistas Nordic para sala",
    "Suscripción Booking.com Genius Level 3",
    "Royal Canin Feline Health Nutrition Indoor",
    "Mochila The North Face Terra 55L",
    "Nike Air Zoom Pegasus 40",
    "Yamaha YZF-R3 ABS 2024",
    "PlayStation 5 Edición Digital",
    "Libro 'Cocina sana para disfrutar' – Isasaweis",
    "Colección Blu-ray John Wick Trilogía",
    "Planta Sansevieria en maceta decorativa",
    "Sombrilla Tommy Bahama con anclaje de arena",
    "Correa retráctil Flexi Giant 8m",
    "Botas Merrell Moab 3 Mid Waterproof",
    "Leggings deportivos Gymshark Adapt",
    "Tesla Model 3 Long Range AWD 2024",
    "Logitech G502 HERO RGB 25K",
    "Kit de Yoga Gaiam Essentials con mat y bloques",
    "Libro 'La chica del tren' de Paula Hawkins",
    "Silla ergonómica SIHOO M18 con soporte lumbar",
    "Suscripción Booking.com Genius Level 3",
    "Arnés Julius-K9 IDC Power para perros",
    "Bicicleta Trek Marlin 7 con suspensión delantera",
    "Creatina Micronizada Optimum Nutrition 300g",
    "Yamaha YZF-R3 ABS 2024",
    "Teclado mecánico Razer BlackWidow V4",
    "Suscripción anual a FitMenCook App",
    "The Legend of Zelda: Tears of the Kingdom",
    "Escritorio eléctrico FLEXISPOT EG1",
    "Panel solar portátil BigBlue 28W USB",
    "Royal Canin Feline Health Nutrition Indoor",
    "Mochila The North Face Terra 55L",
    "Bicicleta Estática Schwinn IC4 con Bluetooth",
    "Tesla Model 3 Long Range AWD 2024",
    "Auriculares HyperX Cloud II Wireless",
    "Suscripción anual a la app Calm Premium",
    "Colección Blu-ray 'Antes del amanecer' trilogía",
    "Set de 3 macetas cerámicas estilo nórdico",
    "Anker PowerCore 26800mAh con carga rápida",
    "Correa retráctil Flexi Giant 8m",
    "Botas Merrell Moab 3 Mid Waterproof",
    "Producto destacado relacionado con: camisetas running",
    "Yamaha YZF-R3 ABS 2024",
    "Garmin Fenix 7 Solar",
    "Colchoneta Manduka PRO Yoga Mat 6mm",
    "Boxset Blu-ray Sherlock BBC completa",
    "Tira LED Govee RGBIC con control app",
    "Sombrilla Tommy Bahama con anclaje de arena",
    "Arnés Julius-K9 IDC Power para perros",
    "Bicicleta Trek Marlin 7 con suspensión delantera",
    "Producto destacado relacionado con: entrenamiento en casa",
    "Yamaha YZF-R3 ABS 2024",
    "Samsung Smart TV 55” 4K UHD Crystal",
    "Libro 'Veganomicon' – Cocina vegana gourmet",
    "Colección Blu-ray Star Wars Saga",
    "Philips Hue White & Color Ambiance Kit",
    "Suscripción Booking.com Genius Level 3",
    "Royal Canin Feline Health Nutrition Indoor",
    "Botas Merrell Moab 3 Mid Waterproof",
    "Proteína Gold Standard 100% Whey 2.27 kg",
    "Tesla Model 3 Long Range AWD 2024",
    "Jabra Elite 7 Active True Wireless",
    "Set de Tuppers Rubbermaid Brilliance BPA-Free",
    "Juego de mesa Catan Edición 25 Aniversario",
    "iRobot Roomba j7+ con estación de vaciado"
  ]
}

df_busquedas = pd.DataFrame(data)

# --- Modelo TF-IDF + KNN ---
tfidf = TfidfVectorizer()
X = tfidf.fit_transform(df_busquedas["busqueda"])
knn_model = NearestNeighbors(n_neighbors=3, metric="cosine")
knn_model.fit(X)

# --- Función con umbral de similitud ---
def sugerir_anuncios_tfidf(user_input, umbral=0.6):
    vec = tfidf.transform([user_input])
    distancias, indices = knn_model.kneighbors(vec)

    st.write("🔍 Búsquedas similares encontradas:", df_busquedas.iloc[indices[0]]["busqueda"].tolist())
    st.write("📉 Distancias (cuanto más bajo, mejor):", distancias[0].tolist())

    # Filtrar resultados por similitud (distancia < umbral)
    sugerencias = []
    for i, dist in enumerate(distancias[0]):
        if dist < umbral:
            anuncio = df_busquedas.iloc[indices[0][i]]["anuncio_sugerido"]
            sugerencias.append(anuncio)

    if not sugerencias:
        sugerencias = ["⚠️ No hay coincidencias suficientemente similares."]

    return list(set(sugerencias))

# --- Función por tema de interés ---
def sugerir_anuncios_por_tema(busqueda_usuario):
    busqueda_usuario_lower = busqueda_usuario.lower()
    temas_relacionados = df_busquedas[df_busquedas["busqueda"].str.contains(busqueda_usuario_lower, case=False)]["tema_interes"].unique()
    sugerencias = []

    if len(temas_relacionados) > 0:
        for tema in temas_relacionados:
            anuncios_posibles = df_busquedas[df_busquedas["tema_interes"] == tema]["anuncio_sugerido"].tolist()
            sugerencias.extend(anuncios_posibles)
    else:
        sugerencias = ["Anuncios generales: descubre nuevas ofertas."]
    return list(set(sugerencias))[:5]

# --- UI con Streamlit ---
st.set_page_config(page_title="🔍 Sugeridor de Anuncios", layout="centered")

st.title("🧠 Sugeridor de Anuncios con IA")
st.markdown("Ingresa una búsqueda para recibir sugerencias relevantes:")

user_input = st.text_input("¿Qué estás buscando?", placeholder="Ej: smartwatch para correr, drones con cámara")

if user_input:
    st.subheader("📌 Basado en Tema de Interés:")
    sugerencias_tema = sugerir_anuncios_por_tema(user_input)
    for sug in sugerencias_tema:
        st.info(f"📎 {sug}")

    st.subheader("🤖 Basado en Similitud (TF-IDF + KNN):")
    sugerencias_tfidf = sugerir_anuncios_tfidf(user_input)
    for sug in sugerencias_tfidf:
        st.success(f"👉 {sug}")

st.markdown("---")
st.subheader("🗃️ Dataset utilizado")
st.dataframe(df_busquedas)

st.caption("Este demo usa TF-IDF y KNN para encontrar anuncios similares. El umbral filtra similitudes débiles para evitar resultados genéricos.")
